# Generated by Django 4.2.6 on 2024-01-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_chatview_send_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatview',
            old_name='textconetnt',
            new_name='textcontent',
        ),
    ]
