# Generated by Django 4.2.6 on 2024-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_textconetnt_chatview_textcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatview',
            name='textcontent',
            field=models.TextField(),
        ),
    ]
